### ISSUE TITLE
readSource('FAO', 'FSCrop') breaks moinput

### ISSUE THREAD

**Issue by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [pik-piam/moinput#17]
Somebody put a data file somewhere that can't be read and thus broke `moinput`. 
```
> Rscript -e "library(moinput); readSource('FAO', 'FSCrop')"
Global .Rprofile loaded!
Loading required package: magclass
Loading required package: methods

Attaching package: 'magclass'

The following object is masked from 'package:grid':

    getNames

Loading required package: madrat
Run readSource("FAO", "FSCrop")
Error in unserialize(readBin(zz, raw(), nbyte_metadata)) : 
  cannot read workspace version 3 written by R 3.6.1; need R 3.5.0 or newer
Calls: readSource -> .getData -> .getData -> read.magpie -> unserialize
Exit readSource("FAO", "FSCrop") in 10.25 seconds
Execution halted
```
The people who came up with the idea for madrat probably know how to find that file.

**Comment by dklein-pik** [comment]
Should be fixed now.

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
Is there any diagnosis what caused this?  In other words: are there any safeguards against users with R version newer than that on the cluster contaminating the cache with unreadable files?

**Comment by dklein-pik** [comment]
No, unfortunately not. When writing the file with a newer R version there is the option to use the old workspace format (version=2). However, there is nosafeguards. Installing the latest R version on the cluster should solve the problem, shouldn't it?

**Comment by tscheypidi** [comment]
I think madrat should not crash only because of faulty cache files. My suggestion to solve this issue is to catch errors during cache readings and just simply ignore the cache files if they cannot be read.

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
> No, unfortunately not. When writing the file with a newer R version there is the option to use the old workspace format (version=2). However, there is nosafeguards. Installing the latest R version on the cluster should solve the problem, shouldn't it?

But the file in question was written by `madrat`, no? So it could be changed to always use the old workspace format, and depend on R >= 3.5.0 when R is updated on the cluster and the `version = 2` change is undone.

**Comment by tscheypidi** [comment]
from version 1.63 on madrat will ignore malformed cache files and rerun calculations instead
