### ISSUE TITLE
calcTimePref() is missing units

### ISSUE THREAD

**Issue by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [pik-piam/moinput#30]
https://github.com/pik-piam/moinput/blob/062bbac89e93ba978eac65717c01764cf9dddcfd/R/calcTimePref.R#L20

**Comment by LaviniaBaumstark** [comment]
this parameter has no unit

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
> this parameter has no unit

Well, why not mentioning that?  In the spirit of transparency.  Other files "without units" are using
`1`, `dimensionless`, `NA`, `none`,  or `ratio`.
