### ISSUE TITLE
calcOutput("EnergyEffPaths") produces missing entries

### ISSUE THREAD

**Issue by MariannaR** [pik-piam/moinput#56]
This is the head of the file p29_efficiency_growth.cs4r :

`
* description: Efficiency pathways for CES variables outside the calibration CES nest
* unit: energy efficiency paths
* origin: calcOutput(type = "EnergyEffPaths", file = "p29_efficiency_growth.cs4r", round = 6) (madrat 1.75.4 | moinput 9.337.0)
* creation date: Tue Apr 21 10:37:48 2020
1993,LAM,(Missing),gdp_SSP1,(Missing),(Missing),fealelb,0.518706
1993,OAS,(Missing),gdp_SSP1,(Missing),(Missing),fealelb,0.430603
1993,SSA,(Missing),gdp_SSP1,(Missing),(Missing),fealelb,0.438691
1993,EUR,(Missing),gdp_SSP1,(Missing),(Missing),fealelb,0.636978
1993,NEU,(Missing),gdp_SSP1,(Missing),(Missing),fealelb,0.613134
1993,MEA,(Missing),gdp_SSP1,(Missing),(Missing),fealelb,0.465322
`
The problem might also be in calcOutput("FEdemand")

**Comment by piklev** [comment]
Should be solved already since 548e1692d33e5f2d2ea664fb558025192b46cac5 in https://github.com/pik-piam/quitte.git
