### ISSUE TITLE
Dependency DirichletReg can not be met on cluster.

### ISSUE THREAD

**Issue by Loisel** [pik-piam/moinput#8]
With commit 6615a9bf421477bf3ccf34508f3feb8f6962b2ae a dependency on the package `DirichletReg` has been introduced, which depends on `rgl` which requires `X11` which is (obviously) not installed on the cluster.

**Comment by giannou** [comment]
@caviddhen can you find an alternative for the `DirichletReg` package?

**Comment by caviddhen** [comment]
I've removed the problematic functions for now

**Comment by giannou** [comment]
@Loisel to me it looks like the problem is solved for now, do you agree?

**Comment by Loisel** [comment]
OK
